// client/editor/frontend/components/Video.vue
<script>
import {
  initializeStream,
  onReceiveControlMessage,
  onSendEditionCommand,
} from "~/modules/api";

import { VideoPlayer } from "~/modules/video";
import { debounce, retryForever } from "~/modules/futures";

export default {
  name: "Video",
  props: {
    // eslint-disable-next-line vue/require-default-prop
    resource: null,
  },
  data() {
    return {
      videoResolution: null,
      desiredResolution: null,
      pc: null,
      videoChannel: null,
      controlChannel: null,
      stateMsg: null,
    };
  },
  computed: {
    loading() {
      return (
        !this.videoResolution ||
        !this.desiredResolution ||
        this.videoResolution.width !== this.desiredResolution.width ||
        this.videoResolution.height !== this.desiredResolution.height
      );
    },
  },
  watch: {
    resource(resource) {
      if (resource.description.id !== "triangle") return;
      if (this.videoChannel == null) return;
      if (this.videoChannel.readyState !== "open") return;

      for (const property of resource.properties) {
        let editionEvent = null;

        if (property.name === "color") {
          editionEvent = JSON.stringify({
            id: crypto.randomUUID(),
            event: "color",
            color: property.value,
          });
        } else if (property.name === "speed") {
          editionEvent = JSON.stringify({
            id: crypto.randomUUID(),
            event: "speed",
            speed: property.value,
          });
        }

        if (editionEvent) {
          onSendEditionCommand(editionEvent);
          this.videoChannel.send(editionEvent);
        }
      }
    },
  },
  mounted() {
    const videoElement = document.getElementById("video");

    this.initialize(videoElement);
    this.stateMsg = "Connecting...";
  },
  methods: {
    initialize(videoElement) {
      const videoPlayer = new VideoPlayer(videoElement, () => {});

      console.log("Initializing WebRTC...");

      if (this.videoChannel != null) {
        this.videoChannel.close();
        this.videoChannel = null;
      }

      if (this.controlChannel != null) {
        this.controlChannel.close();
        this.controlChannel = null;
      }

      if (this.pc !== null) {
        this.pc.close();
        this.pc = null;
      }

      this.pc = new RTCPeerConnection({
        urls: [{ url: "stun:stun.l.google.com:19302" }],
      });

      this.pc.onnegotiationneeded = async () => {
        this.pc.setLocalDescription(await this.pc.createOffer());
      };

      this.pc.onicecandidate = (iceEvent) => {
        console.log(iceEvent);

        if (iceEvent.candidate === null) {
          retryForever(
            initializeStream.bind(null, this.pc.localDescription)
          ).then((remoteDescription) => {
            this.pc.setRemoteDescription(remoteDescription);
          });
        }
      };

      this.pc.oniceconnectionstatechange = () => {
        if (this.pc.iceConnectionState === "disconnected") {
          console.log("Disconnected");

          window.setTimeout(() => {
            videoElement.pause();
            videoElement.removeAttribute("src");
            videoElement.load();

            this.videoResolution = null;
            this.stateMsg = "Reconnecting...";

            this.initialize(videoElement);
          }, 600);
        }
      };

      this.videoChannel = this.pc.createDataChannel("video");
      this.controlChannel = this.pc.createDataChannel("control");

      videoElement.addEventListener("loadedmetadata", (event) => {
        const width = event.target.videoWidth;
        const height = event.target.videoHeight;

        console.log("Video resolution is now:", width, "x", height, ".");
        this.videoResolution = { width, height };
        this.stateMsg = null;

        observer.observe(videoElement.parentElement);
      });

      const observer = new ResizeObserver(
        debounce(() => {
          // Ensure our resolution is a multiple of two.
          const width = videoElement.parentElement.offsetWidth & ~1;
          const height = videoElement.parentElement.offsetHeight & ~1;

          if (width === 0 || height === 0) return;

          console.log("Desired resolution is now:", width, "x", height, ".");
          this.desiredResolution = { width, height };

          this.stateMsg = "Resizing...";

          this.videoChannel.send(
            JSON.stringify({
              event: "resize",
              width,
              height,
            })
          );
        }, 250)
      );

      this.videoChannel.onerror = (error) => {
        console.error(error.error);
      };
      this.videoChannel.onopen = () => {
        console.log("Video channel is now open.");
      };
      this.videoChannel.onclose = () => {
        console.log("Video channel is now closed.");
        observer.disconnect();
      };
      this.videoChannel.onmessage = (msg) => {
        videoPlayer.push(msg.data);
      };
      this.videoChannel.ondatachannel = (evt) => {
        console.log("video data channel: ", evt);
      };
      this.controlChannel.onopen = (evt) => {
        console.log("Control channel is now open: ", evt);
      };
      this.controlChannel.onclose = (evt) => {
        console.log("Control channel is now closed: ", evt);
      };
      this.controlChannel.ondatachannel = (evt) => {
        console.log("control data channel: ", evt);
      };
      this.controlChannel.onmessage = (msg) => {
        const jsonMsg = new TextDecoder().decode(msg.data);
        onReceiveControlMessage(jsonMsg);
      };
    },
    backgroundURL() {
      let width = 1024;
      let height = 768;

      if (this.desiredResolution) {
        width = this.desiredResolution.width;
        height = this.desiredResolution.height;
      }

      return {
        "--bg-url":
          "url(https://source.unsplash.com/random/" +
          width +
          "x" +
          height +
          "?3d-render)",
      };
    },
  },
};
</script>

<template>
  <div id="video-container" :style="backgroundURL()" class="d-flex">
    <video id="video" :class="{ show: !loading }"></video>
    <v-progress-linear
      v-if="loading"
      id="loading"
      indeterminate
      color="yellow darken-2"
    ></v-progress-linear>
    <code v-if="videoResolution" id="resolution" :class="{ show: !loading }">
      {{ videoResolution.width }}x{{ videoResolution.height }}</code
    >
    <h3 v-if="stateMsg" id="connecting">
      <v-progress-circular
        indeterminate
        color="white"
        :size="30"
      ></v-progress-circular>
      <span>{{ stateMsg }}</span>
    </h3>
  </div>
</template>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
#video-container {
  background-color: black;
  overflow: hidden;
  position: relative;
  background: linear-gradient(
      to top right,
      rgba(100, 115, 201, 0.7),
      rgba(25, 32, 72, 0.7)
    ),
    no-repeat center/cover var(--bg-url);
}

#video {
  position: absolute;
  object-fit: cover;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  max-width: 100%;
  max-height: 100%;
  margin: auto;
  opacity: 0;
  transition: opacity 0.5s linear;
}

#video.show {
  opacity: 1;
}

#loading {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
}

#resolution {
  position: absolute;
  border-radius: 1em;
  background-color: gray;
  color: black;
  top: 1em;
  right: 1em;
  opacity: 0;
  transition: opacity 0.5s linear;
  user-select: none;
  font-size: smaller;
}

#resolution.show {
  opacity: 0.5;
}

#connecting {
  position: absolute;
  left: 0;
  right: 0;
  top: 48%;
  text-align: center;
  color: silver;
  animation: glow 1s infinite alternate;
}

#connecting .v-progress-circular + span {
  margin-left: 1em;
}

@keyframes glow {
  from {
    opacity: 0.2;
  }

  to {
    opacity: 1;
  }
}
</style>

// client/runtime/frontend/src/components/Video.svelte
<script context="module" lang="ts">
  export type Resolution = { width: number; height: number };
</script>

<script lang="ts">
  import { onMount } from "svelte";
  import resize from "@/actions/resize";
  import videoPlayer, { PushableHTMLVideoElement } from "@/actions/videoPlayer";
  import { debounce, retry } from "@/lib/promises";
  import { initializeStream, onReceiveControlMessage } from "@/api";
  import { statusStore } from "@/stores/statusBarData";
  import log from "@/lib/log";

  const reconnectionTimeout = 600;

  const resizeVideoTimeout = 300;

  export let desiredResolution: Resolution | null = null;

  export let color: string | null = null;

  let resolution: Resolution | null = null;

  let videoElement: HTMLVideoElement;

  let videoChannel: RTCDataChannel | null;

  let controlChannel: RTCDataChannel | null;

  let peerConnection: RTCPeerConnection | null;

  let videoAlreadyRendered = false;

  let loading = false;

  $statusStore = "Connecting...";

  onMount(async () => {
    initialize();
  });

  // Destroys all peer connection related resources when possible
  const destroyResources = () => {
    if (videoChannel !== null) {
      videoChannel.close();
      videoChannel = null;
    }

    if (controlChannel !== null) {
      controlChannel.close();
      controlChannel = null;
    }

    if (peerConnection !== null) {
      peerConnection.close();
      peerConnection = null;
    }
  };

  const initialize = () => {
    if (!videoElement) {
      log.error("video", "Video element couldn't be found");
      return;
    }

    log.debug("video", "Initializing WebRTC");

    peerConnection = new RTCPeerConnection({
      iceServers: [{ urls: ["stun:stun.l.google.com:19302"] }],
    });

    peerConnection.onnegotiationneeded = async () => {
      if (peerConnection) {
        peerConnection.setLocalDescription(await peerConnection.createOffer());
      }
    };

    peerConnection.onicecandidate = async (iceEvent) => {
      log.debug("video", iceEvent);

      if (peerConnection && iceEvent.candidate === null) {
        const remoteDescription = await retry(() => {
          if (peerConnection && peerConnection.localDescription) {
            return initializeStream(peerConnection.localDescription);
          }

          return Promise.resolve(null);
        });

        if (remoteDescription) {
          peerConnection.setRemoteDescription(remoteDescription);
        }
      }
    };

    peerConnection.oniceconnectionstatechange = () => {
      if (
        peerConnection &&
        peerConnection.iceConnectionState === "disconnected"
      ) {
        log.debug("video", "Disconnected");

        window.setTimeout(() => {
          if (videoElement) {
            videoElement.pause();
            videoElement.removeAttribute("src");
            videoElement.load();
          }

          $statusStore = "Reconnecting...";

          destroyResources();

          initialize();
        }, reconnectionTimeout);
      }
    };

    videoChannel = peerConnection.createDataChannel("video");

    controlChannel = peerConnection.createDataChannel("control");

    videoElement.addEventListener("loadedmetadata", (event) => {
      if (videoElement && event.target instanceof HTMLVideoElement) {
        if (!videoAlreadyRendered) {
          videoAlreadyRendered = true;
        }
        const { videoWidth, videoHeight } = event.target;

        log.debug(
          "video",
          `Video resolution is now: ${videoWidth}x${videoHeight}.`
        );

        loading = false;
        $statusStore = null;
        resolution = desiredResolution;
      }
    });

    videoChannel.onerror = (error: unknown) => {
      log.error("video", error);
    };

    videoChannel.onopen = () => {
      log.debug("video", "Video channel is now open.");
      if (videoChannel && color) {
        videoChannel.send(
          JSON.stringify({ event: "color", id: "background", color })
        );
      }
    };

    videoChannel.onclose = () => {
      log.debug("video", "Video channel is now closed.");
    };

    videoChannel.onmessage = async (message) => {
      // videoElement is augmented with the `videoPlayer` action and will
      // provide a `push` function.
      (videoElement as PushableHTMLVideoElement).push(
        // In Tauri message.data is an ArrayBuffer
        // while it's a Blob in browser
        message.data instanceof ArrayBuffer
          ? message.data
          : await message.data.arrayBuffer()
      );
    };

    controlChannel.onopen = (event) => {
      log.debug("video", log.json`Control channel is now open: ${event}`);
    };

    controlChannel.onclose = (event) => {
      log.debug("video", log.json`Control channel is now closed: ${event}`);
    };

    controlChannel.onmessage = async (
      message: MessageEvent<ArrayBuffer | Blob>
    ) => {
      const jsonMsg = new TextDecoder().decode(
        // In Tauri message.data is an ArrayBuffer
        // while it's a Blob in browser
        message.data instanceof ArrayBuffer
          ? message.data
          : await message.data.arrayBuffer()
      );

      onReceiveControlMessage(jsonMsg);
    };
  };

  const resizeVideo = debounce((desiredResolution: Resolution) => {
    if (!videoAlreadyRendered) {
      return;
    }

    // Ensure our resolution is a multiple of two.
    const height = desiredResolution.height & ~1;
    const width = desiredResolution.width & ~1;

    if (width == 0 || height == 0) {
      return;
    }

    log.debug("video", `Desired resolution is now: ${width}x${height}`);

    if (videoChannel && videoChannel.readyState === "open") {
      videoChannel.send(JSON.stringify({ event: "resize", width, height }));
    }
  }, resizeVideoTimeout);

  const onVideoResize = ({ width, height }: DOMRectReadOnly) => {
    desiredResolution = {
      width: Math.round(width),
      height: Math.round(height),
    };
  };

  $: if (
    resolution &&
    desiredResolution &&
    (resolution.height !== desiredResolution.height ||
      resolution.width !== desiredResolution.width)
  ) {
    resizeVideo(desiredResolution);
    $statusStore = "Resizing...";
    loading = true;
  }
</script>

<div class="video-container" use:resize={onVideoResize}>
  <video
    class="video"
    class:opacity-0={loading}
    class:opacity-100={!loading}
    use:videoPlayer
    bind:this={videoElement}
  >
    <track kind="captions" />
  </video>
  {#if $statusStore}
    <h3 class="status">
      <span>{$statusStore}</span>
    </h3>
  {/if}
</div>

<style lang="postcss">
  .video-container {
    @apply h-full w-full overflow-hidden relative text-white;
  }

  .video {
    @apply absolute object-cover inset-0 w-full h-full m-auto transition duration-200;
  }

  .status {
    @apply absolute left-0 right-0 top-1/2 text-center;
    animation: glow 1s infinite alternate;
  }

  @keyframes glow {
    from {
      opacity: 0.2;
    }

    to {
      opacity: 1;
    }
  }
</style>
