// client/editor-vue3/frontend/src/pages/Home.vue
<script lang="ts" setup>
import Panel from "@/components/Panel.vue";
import TopBar from "@/components/TopBar.vue";
</script>

<template>
  <div class="h-screen w-full">
    <TopBar />
    <div class="h-[calc(100vh-1.75rem)] w-full">
      <div class="flex flex-row h-full w-full">
        <div class="flex flex-col flex-shrink-0 w-[1200px]">
          <Panel>
            <template #header> Untitled Document </template>
          </Panel>
        </div>
        <div class="flex-shrink-0 w-1" />
        <div class="flex flex-col w-full">
          <Panel>
            <template #header> Properties </template>
          </Panel>
          <div class="flex-shrink-0 h-1" />
          <Panel>
            <template #header> Layer Tree </template>
          </Panel>
        </div>
      </div>
    </div>
  </div>
</template>

// crates/lgn-runtime-gui/frontend/src/pages/Home.svelte
<script lang="ts">
  import { Panel } from "@lgn/frontend/src/components/panel";
  import TopBar from "@lgn/frontend/src/components/TopBar.svelte";
  import StatusBar from "@lgn/frontend/src/components/StatusBar.svelte";
  import RemoteWindow from "@lgn/frontend/src/components/RemoteWindow.svelte";
  import { Resolution } from "@lgn/frontend/src/lib/types";

  let desiredVideoResolution: Resolution | null;
</script>

<div class="root">
  <TopBar />
  <div class="content-wrapper">
    <div class="content">
      <div class="main-content">
        <Panel>
          <span slot="header">
            <span>Main Stream</span>
            {#if desiredVideoResolution}
              <span>
                - {desiredVideoResolution.width}x{desiredVideoResolution.height}
              </span>
            {/if}
          </span>
          <div class="video-container" slot="content">
            <RemoteWindow
              serverType="runtime"
              bind:desiredResolution={desiredVideoResolution}
            />
          </div>
        </Panel>
      </div>
    </div>
  </div>
  <StatusBar />
</div>

<style lang="postcss">
  .root {
    @apply h-screen w-full;
  }

  .content-wrapper {
    @apply h-[calc(100vh-3.5rem)] w-full overflow-auto;
  }

  .content {
    @apply flex flex-row h-full w-full;
  }

  .main-content {
    @apply flex flex-col w-full;
  }

  .video-container {
    @apply h-full w-full;
  }
</style>
