// client/editor/frontend/components/Video.vue
<script>
import {
  initializeStream,
  onReceiveControlMessage,
  onSendEditionCommand,
} from "~/modules/api";

import { VideoPlayer } from "~/modules/video";
import { debounce, retryForever } from "~/modules/futures";

export default {
  name: "Video",
  props: {
    // eslint-disable-next-line vue/require-default-prop
    resource: null,
  },
  data() {
    return {
      videoResolution: null,
      desiredResolution: null,
      pc: null,
      videoChannel: null,
      controlChannel: null,
      stateMsg: null,
    };
  },
  computed: {
    loading() {
      return (
        !this.videoResolution ||
        !this.desiredResolution ||
        this.videoResolution.width !== this.desiredResolution.width ||
        this.videoResolution.height !== this.desiredResolution.height
      );
    },
  },
  watch: {
    resource(resource) {
      if (resource.description.id !== "triangle") return;
      if (this.videoChannel == null) return;
      if (this.videoChannel.readyState !== "open") return;

      for (const property of resource.properties) {
        let editionEvent = null;

        if (property.name === "color") {
          editionEvent = JSON.stringify({
            id: crypto.randomUUID(),
            event: "color",
            color: property.value,
          });
        } else if (property.name === "speed") {
          editionEvent = JSON.stringify({
            id: crypto.randomUUID(),
            event: "speed",
            speed: property.value,
          });
        }

        if (editionEvent) {
          onSendEditionCommand(editionEvent);
          this.videoChannel.send(editionEvent);
        }
      }
    },
  },
  mounted() {
    const videoElement = document.getElementById("video");

    this.initialize(videoElement);
    this.stateMsg = "Connecting...";
  },
  methods: {
    initialize(videoElement) {
      const videoPlayer = new VideoPlayer(videoElement, () => {});

      console.log("Initializing WebRTC...");

      if (this.videoChannel != null) {
        this.videoChannel.close();
        this.videoChannel = null;
      }

      if (this.controlChannel != null) {
        this.controlChannel.close();
        this.controlChannel = null;
      }

      if (this.pc !== null) {
        this.pc.close();
        this.pc = null;
      }

      this.pc = new RTCPeerConnection({
        urls: [{ url: "stun:stun.l.google.com:19302" }],
      });

      this.pc.onnegotiationneeded = async () => {
        this.pc.setLocalDescription(await this.pc.createOffer());
      };

      this.pc.onicecandidate = (iceEvent) => {
        console.log(iceEvent);

        if (iceEvent.candidate === null) {
          retryForever(
            initializeStream.bind(null, this.pc.localDescription)
          ).then((remoteDescription) => {
            this.pc.setRemoteDescription(remoteDescription);
          });
        }
      };

      this.pc.oniceconnectionstatechange = () => {
        if (this.pc.iceConnectionState === "disconnected") {
          console.log("Disconnected");

          window.setTimeout(() => {
            videoElement.pause();
            videoElement.removeAttribute("src");
            videoElement.load();

            this.videoResolution = null;
            this.stateMsg = "Reconnecting...";

            this.initialize(videoElement);
          }, 600);
        }
      };

      this.videoChannel = this.pc.createDataChannel("video");
      this.controlChannel = this.pc.createDataChannel("control");

      videoElement.addEventListener("loadedmetadata", (event) => {
        const width = event.target.videoWidth;
        const height = event.target.videoHeight;

        console.log("Video resolution is now:", width, "x", height, ".");
        this.videoResolution = { width, height };
        this.stateMsg = null;

        observer.observe(videoElement.parentElement);
      });

      const observer = new ResizeObserver(
        debounce(() => {
          // Ensure our resolution is a multiple of two.
          const width = videoElement.parentElement.offsetWidth & ~1;
          const height = videoElement.parentElement.offsetHeight & ~1;

          if (width === 0 || height === 0) return;

          console.log("Desired resolution is now:", width, "x", height, ".");
          this.desiredResolution = { width, height };

          this.stateMsg = "Resizing...";

          this.videoChannel.send(
            JSON.stringify({
              event: "resize",
              width,
              height,
            })
          );
        }, 250)
      );

      this.videoChannel.onerror = (error) => {
        console.error(error.error);
      };
      this.videoChannel.onopen = () => {
        console.log("Video channel is now open.");
      };
      this.videoChannel.onclose = () => {
        console.log("Video channel is now closed.");
        observer.disconnect();
      };
      this.videoChannel.onmessage = (msg) => {
        videoPlayer.push(msg.data);
      };
      this.videoChannel.ondatachannel = (evt) => {
        console.log("video data channel: ", evt);
      };
      this.controlChannel.onopen = (evt) => {
        console.log("Control channel is now open: ", evt);
      };
      this.controlChannel.onclose = (evt) => {
        console.log("Control channel is now closed: ", evt);
      };
      this.controlChannel.ondatachannel = (evt) => {
        console.log("control data channel: ", evt);
      };
      this.controlChannel.onmessage = (msg) => {
        const jsonMsg = new TextDecoder().decode(msg.data);
        onReceiveControlMessage(jsonMsg);
      };
    },
    backgroundURL() {
      let width = 1024;
      let height = 768;

      if (this.desiredResolution) {
        width = this.desiredResolution.width;
        height = this.desiredResolution.height;
      }

      return {
        "--bg-url":
          "url(https://source.unsplash.com/random/" +
          width +
          "x" +
          height +
          "?3d-render)",
      };
    },
  },
};
</script>

<template>
  <div id="video-container" :style="backgroundURL()" class="d-flex">
    <video id="video" :class="{ show: !loading }"></video>
    <v-progress-linear
      v-if="loading"
      id="loading"
      indeterminate
      color="yellow darken-2"
    ></v-progress-linear>
    <code v-if="videoResolution" id="resolution" :class="{ show: !loading }">
      {{ videoResolution.width }}x{{ videoResolution.height }}</code
    >
    <h3 v-if="stateMsg" id="connecting">
      <v-progress-circular
        indeterminate
        color="white"
        :size="30"
      ></v-progress-circular>
      <span>{{ stateMsg }}</span>
    </h3>
  </div>
</template>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
#video-container {
  background-color: black;
  overflow: hidden;
  position: relative;
  background: linear-gradient(
      to top right,
      rgba(100, 115, 201, 0.7),
      rgba(25, 32, 72, 0.7)
    ),
    no-repeat center/cover var(--bg-url);
}

#video {
  position: absolute;
  object-fit: cover;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  max-width: 100%;
  max-height: 100%;
  margin: auto;
  opacity: 0;
  transition: opacity 0.5s linear;
}

#video.show {
  opacity: 1;
}

#loading {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
}

#resolution {
  position: absolute;
  border-radius: 1em;
  background-color: gray;
  color: black;
  top: 1em;
  right: 1em;
  opacity: 0;
  transition: opacity 0.5s linear;
  user-select: none;
  font-size: smaller;
}

#resolution.show {
  opacity: 0.5;
}

#connecting {
  position: absolute;
  left: 0;
  right: 0;
  top: 48%;
  text-align: center;
  color: silver;
  animation: glow 1s infinite alternate;
}

#connecting .v-progress-circular + span {
  margin-left: 1em;
}

@keyframes glow {
  from {
    opacity: 0.2;
  }

  to {
    opacity: 1;
  }
}
</style>

// client/editor-svelte/frontend/src/components/Video.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    initializeStream,
    onReceiveControlMessage,
    onSendEditionCommand,
    VideoPlayer,
    debounce,
    retryForever,
  } from "@/lib";

  export let resource: any = null;

  let videoElement: any = null;

  let videoResolution: any = null;

  let desiredResolution: any = null;

  let videoChannel: any = null;

  let controlChannel: any = null;

  let stateMsg: any = null;

  let pc: any = null;

  onMount(() => {
    initialize(videoElement);

    stateMsg = "Connecting...";
  });

  const initialize = (videoElement: HTMLVideoElement) => {
    const videoPlayer = new VideoPlayer(videoElement);

    console.log("Initializing WebRTC...");

    if (videoChannel !== null) {
      videoChannel.close();
      videoChannel = null;
    }

    if (controlChannel !== null) {
      controlChannel.close();
      controlChannel = null;
    }

    if (pc !== null) {
      pc.close();
      pc = null as any;
    }

    pc = new RTCPeerConnection({
      urls: [{ url: "stun:stun.l.google.com:19302" }],
    } as any);

    pc.onnegotiationneeded = async () => {
      pc.setLocalDescription(await pc.createOffer());
    };

    pc.onicecandidate = async (iceEvent: any) => {
      console.log(iceEvent);

      if (iceEvent.candidate === null) {
        retryForever(() => initializeStream(pc.localDescription!)).then(
          (remoteDescription) => {
            pc.setRemoteDescription(remoteDescription);
          }
        );
      }
    };

    pc.oniceconnectionstatechange = async () => {
      if (pc.iceConnectionState === "disconnected") {
        console.log("Disconnected");

        window.setTimeout(() => {
          videoElement.pause();
          videoElement.removeAttribute("src");
          videoElement.load();

          videoResolution = null;
          stateMsg = "Reconnecting...";

          initialize(videoElement);
        }, 600);
      }
    };

    videoChannel = pc.createDataChannel("video");
    controlChannel = pc.createDataChannel("control");

    videoElement.addEventListener("loadedmetadata", (event) => {
      const width = (event.target! as any).videoWidth;
      const height = (event.target! as any).videoHeight;

      console.log("Video resolution is now:", width, "x", height, ".");
      videoResolution = { width: width, height: height };
      stateMsg = null;

      observer.observe(videoElement.parentElement!);
    });

    const observer = new ResizeObserver(
      debounce(() => {
        // Ensure our resolution is a multiple of two.
        const width = videoElement.parentElement!.offsetWidth & ~1;
        const height = videoElement.parentElement!.offsetHeight & ~1;

        if (width == 0 || height == 0) {
          return;
        }

        console.log("Desired resolution is now:", width, "x", height, ".");
        desiredResolution = { width: width, height: height };

        stateMsg = "Resizing...";

        videoChannel.send(
          JSON.stringify({
            event: "resize",
            width: width,
            height: height,
          })
        );
      }, 250)
    );

    videoChannel.onerror = (error: any) => {
      console.log(error.error);
    };

    videoChannel.onopen = () => {
      console.log("Video channel is now open.");
    };

    videoChannel.onclose = () => {
      console.log("Video channel is now closed.");
      observer.disconnect();
    };

    videoChannel.onmessage = (msg: any) => {
      videoPlayer.push(msg.data);
    };

    videoChannel.ondatachannel = (event: any) => {
      console.log("video data channel: ", event);
    };

    controlChannel.onopen = (event: any) => {
      console.log("Control channel is now open: ", event);
    };

    controlChannel.onclose = (event: any) => {
      console.log("Control channel is now closed: ", event);
    };

    controlChannel.ondatachannel = (event: any) => {
      console.log("control data channel: ", event);
    };

    controlChannel.onmessage = (msg: any) => {
      // const jsonMsg = new TextDecoder().decode(msg.data);

      onReceiveControlMessage(msg);
    };
  };

  const backgroundURL = () => {
    let width = 1024;
    let height = 768;

    if (desiredResolution) {
      width = desiredResolution.width;
      height = desiredResolution.height;
    }

    return `--bg-url: url(https://source.unsplash.com/random/${width}x${height}?3d-render)`;
  };

  $: (() => {
    if (
      !resource ||
      resource.description.id !== "triangle" ||
      videoChannel === null ||
      videoChannel.readyState !== "open"
    ) {
      return;
    }

    for (const property of resource.properties) {
      let editionEvent = null;

      switch (property.name) {
        case "color": {
          editionEvent = JSON.stringify({
            id: (crypto as any).randomUUID(),
            event: "color",
            color: property.value,
          });

          break;
        }

        case "speed": {
          editionEvent = JSON.stringify({
            id: (crypto as any).randomUUID(),
            event: "speed",
            speed: property.value,
          });

          break;
        }
      }

      if (editionEvent) {
        onSendEditionCommand(editionEvent);

        videoChannel.send(editionEvent);
      }
    }
  })();

  $: loading =
    !videoResolution ||
    !desiredResolution ||
    videoResolution.width !== desiredResolution.width ||
    videoResolution.height !== desiredResolution.height;
</script>

<div
  id="video-container"
  class="h-full w-full bg-black overflow-hidden relative"
  style={backgroundURL()}
>
  <!-- svelte-ignore a11y-media-has-caption -->
  <video
    id="video"
    class="absolute object-cover inset-0 max-w-full max-h-full opacity-0 m-auto"
    class:show={!loading}
    bind:this={videoElement}
  />
  <!-- <v-progress-linear
    id="loading"
    indeterminate
    color="yellow darken-2"
    v-if="loading"
  /> -->
  {#if videoResolution}
    <code
      id="resolution"
      class="absolute rounded-2xl bg-gray-400 text-black top-4 right-4 opacity-0 text-sm"
      class:show={!loading}
    >
      {videoResolution.width}x{videoResolution.height}</code
    >
  {/if}
  {#if stateMsg}
    <h3
      id="connecting"
      class="absolute left-0 right-0 top-1/2 text-center text-gray-400"
    >
      <!-- <v-progress-circular indeterminate color="white" :size="30" /> -->
      <span>{stateMsg}</span>
    </h3>
  {/if}
</div>

<style>
  #video-container {
    background: linear-gradient(
        to top right,
        rgba(100, 115, 201, 0.7),
        rgba(25, 32, 72, 0.7)
      ),
      no-repeat center/cover var(--bg-url);
  }

  #video {
    transition: opacity 0.5s linear;
  }

  #video.show {
    opacity: 1;
  }

  #loading {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
  }

  #resolution {
    /* border-radius: 1em; */
    transition: opacity 0.5s linear;
  }

  #resolution.show {
    opacity: 0.5;
  }

  #connecting {
    animation: glow 1s infinite alternate;
  }

  #connecting .v-progress-circular + span {
    margin-left: 1em;
  }

  @keyframes glow {
    from {
      opacity: 0.2;
    }

    to {
      opacity: 1;
    }
  }
</style>
