// lib/browser/frontend/src/components/TopBar.svelte
<script lang="ts">
  import topBarMenu, {
    Id as TopBarMenuId,
    menus as topBarMenus,
  } from "../stores/topBarMenu";
  import userInfo from "../stores/userInfo";
  import log from "../lib/log";
  import clickOutside from "../actions/clickOutside";
  import { startUserAuth } from "../lib/auth";

  export let documentTitle: string | null = null;

  const { data: userInfoData } = userInfo;

  $: userInitials =
    $userInfoData && $userInfoData.given_name && $userInfoData.family_name
      ? `${$userInfoData.given_name[0]}${$userInfoData.family_name[0]}`
      : // TODO: Use an icon
        "Me";

  function onMenuMouseEnter(id: TopBarMenuId) {
    // We set the topBarMenu value (and therefore open said menu dropdown)
    // only when a menu is open
    $topBarMenu && topBarMenu.set(id);
  }

  function onMenuClick(id: TopBarMenuId) {
    // Simple menu dropdown display toggle
    $topBarMenu ? topBarMenu.close() : topBarMenu.set(id);
  }

  function onMenuItemClick(title: string) {
    log.debug("layout:topbar", `Clicked on item ${title}`);
    // When a user clicks on a menu dropdown item, we just close the menu for now
    topBarMenu.close();
  }

  function closeMenu() {
    if ($topBarMenu) {
      topBarMenu.close();
    }
  }

  function authenticate() {
    startUserAuth();
  }
</script>

<div class="root">
  <div use:clickOutside={closeMenu} class="menus">
    <div class="brand">Legion</div>
    {#each topBarMenus as menu (menu.id)}
      <div
        data-testid="menu-{menu.id}"
        class="menu"
        class:bg-gray-400={$topBarMenu === menu.id}
        on:mouseenter={() => onMenuMouseEnter(menu.id)}
        on:click|capture={() => onMenuClick(menu.id)}
      >
        <div class="menu-title">
          {menu.title}
        </div>
        <div
          data-testid="dropdown-{menu.id}"
          class="menu-dropdown"
          class:hidden={$topBarMenu !== menu.id}
        >
          <div class="menu-dropdown-items">
            {#each [`Foo ${menu.title}`, `Bar ${menu.title}`, `Baz ${menu.title}`] as menuItemTitle}
              <div
                class="menu-dropdown-item"
                on:click={() => onMenuItemClick(menu.title)}
              >
                {menuItemTitle}
              </div>
            {/each}
          </div>
        </div>
      </div>
    {/each}
  </div>
  <div class="document-title">
    {#if documentTitle}
      {documentTitle}
    {:else}
      Untitled document
    {/if}
  </div>
  <div class="actions">
    <div
      class="authenticate"
      class:cursor-pointer={!$userInfoData}
      title={$userInfoData
        ? `Welcome back ${$userInfoData.name}`
        : "Authenticate"}
      on:click={$userInfoData ? null : authenticate}
    >
      {userInitials}
    </div>
  </div>
</div>

<style lang="postcss">
  .root {
    @apply h-8 flex flex-row justify-between items-center flex-1 whitespace-nowrap;
  }

  .menus {
    @apply flex flex-row h-full flex-1 space-x-1 justify-center md:justify-start;
  }

  .brand {
    @apply flex items-center italic px-2;
  }

  .menu {
    @apply hidden sm:flex items-center cursor-pointer z-20 hover:bg-gray-500;
  }

  .menu-title {
    @apply px-2;
  }

  .menu-dropdown {
    @apply absolute top-7 rounded-b-sm;
  }

  .menu-dropdown-items {
    @apply bg-gray-800 py-1;
  }

  .menu-dropdown-item {
    @apply hover:bg-gray-500 cursor-pointer px-6 py-0.5;
  }

  .document-title {
    @apply hidden sm:flex;
  }

  .actions {
    @apply justify-end hidden sm:flex items-center flex-1 pr-2;
  }

  .authenticate {
    @apply flex justify-center items-center rounded-full bg-orange-700 bg-opacity-80 h-6 w-6 text-xs text-white font-bold;
  }
</style>

// client/editor-vue3/frontend/src/components/TopBar.vue
<script lang="ts" setup>
import useClickOutside from "@/composables/useClickOutside";
import { Id as MenuId, menus, useTopBarMenu } from "@/stores/topBarMenu";

// Props and events
type Props = {
  documentTitle?: string;
};

defineProps<Props>();

// Reactive values

const topBarMenu = useTopBarMenu();

const { ref: menuSectionRef } = useClickOutside(() => {
  if (topBarMenu.openedMenuId) {
    topBarMenu.close();
  }
});

// Callbacks

const onMenuMouseEnter = (id: MenuId) =>
  // We set the openedMenu value (and therefore open said menu dropdown)
  // only when a menu is open
  topBarMenu.isOpen && topBarMenu.set(id);

const onMenuClick = (id: MenuId) => {
  // Simple menu dropdown display toggle
  topBarMenu.isOpen ? topBarMenu.close() : topBarMenu.set(id);
};

const onMenuItemClick = () => {
  // When a user clicks on a menu dropdown item, we just close the menu
  topBarMenu.close();
  console.log("Executed");
};
</script>

<template>
  <div class="flex flex-row justify-between space-x-2">
    <div
      ref="menuSectionRef"
      class="flex flex-row flex-1 h-7 space-x-1 text-sm"
    >
      <div class="flex items-center italic px-2">Legion</div>
      <div
        v-for="menu in menus"
        :key="menu.id"
        class="flex items-center hover:bg-gray-400 cursor-pointer"
        :class="{ 'bg-gray-400': topBarMenu.openedMenuId === menu.id }"
        @mouseenter="onMenuMouseEnter(menu.id)"
        @click="onMenuClick(menu.id)"
      >
        <div class="px-2">
          {{ menu.title }}
        </div>
        <div
          class="absolute top-7"
          :class="{ hidden: topBarMenu.openedMenuId !== menu.id }"
        >
          <div class="bg-gray-800 py-1 bg-opacity-90">
            <div
              v-for="menuItemTitle in [
                `Foo ${menu.title}`,
                `Bar ${menu.title}`,
                `Baz ${menu.title}`,
              ]"
              :key="menuItemTitle"
              class="cursor-pointer hover:bg-gray-400 px-6 py-0.5"
              @click.stop="onMenuItemClick"
            >
              {{ menuItemTitle }}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div
      class="flex flex-row justify-center items-center flex-1 whitespace-nowrap"
    >
      <template v-if="documentTitle">{{ documentTitle }}</template>
      <template v-else>Untitled document</template>
    </div>
    <div class="flex-1" />
  </div>
</template>
