// client/analytics-web-svelte/src/App.svelte
<script lang="ts">
  import { Router, links, Route, globalHistory } from "svelte-navigator";
  import Home from "@/pages/Home.svelte";
  import About from "@/pages/About.svelte";
  import Log from "@/pages/Log.svelte";
  import Timeline from "@/pages/Timeline.svelte";

  const historyStore = { subscribe: globalHistory.listen };
</script>

<Router>
  <div id="app">
    <div id="nav" use:links>
      <a
        href="/"
        class:router-link-exact-active={$historyStore.location.pathname === "/"}
      >
        Home
      </a>
      |
      <a
        href="/about"
        class:router-link-exact-active={$historyStore.location.pathname ===
          "/about"}
      >
        About
      </a>
    </div>
    <Route path="/"><Home /></Route>
    <Route path="/about"><About /></Route>
    <Route path="/log/:id" let:params><Log id={params.id} /></Route>
    <Route path="/timeline/:id" let:params primary={false}>
      {#key params.id}
        <Timeline id={params.id} />
      {/key}
    </Route>
  </div>
</Router>

<style lang="postcss">
  #app {
    @apply text-center text-[#2c3e50];
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  #nav {
    @apply p-8;
  }

  #nav a {
    @apply font-bold text-[#2c3e50] underline;
  }

  #nav a.router-link-exact-active {
    @apply font-bold text-[#42b983] underline;
  }
</style>

// client/editor/src/App.vue
<template>
  <div id="app">
    <HelloWorld msg="Welcome to Your Vue.js App" />
  </div>
</template>

<script>
import HelloWorld from "./components/HelloWorld.vue";

export default {
  name: "App",
  components: {
    HelloWorld,
  },
};
</script>

<style>
html {
  background-color: #333;
  color: white;
}

#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  margin: 1em 0;
}
</style>
