// client/analytics-web/frontend/src/pages/Timeline.svelte
<script context="module" lang="ts">
  type Thread = {
    streamInfo: Stream;
    spanBlocks: BlockSpansReply[];
  };

  type BeginPan = {
    beginMouseX: number;
    beginMouseY: number;
    viewRange: [number, number];
    beginYOffset: number;
  };

  type BeginDetect = {
    beginMouseX: number;
  };
</script>

<script lang="ts">
  import { link } from "svelte-navigator";
  import {
    BlockSpansReply,
    GrpcWebImpl,
    PerformanceAnalyticsClientImpl,
    ScopeDesc,
  } from "@lgn/proto-telemetry/codegen/analytics";
  import { Block } from "@lgn/proto-telemetry/codegen/block";
  import { Process } from "@lgn/proto-telemetry/codegen/process";
  import { Stream } from "@lgn/proto-telemetry/codegen/stream";
  import { onMount } from "svelte";
  import { formatExecutionTime } from "@/lib/format";

  export let id: string;

  let canvas: HTMLCanvasElement | undefined;
  let processList: Process[] = [];
  let currentProcess: Process | undefined;
  let renderingContext: CanvasRenderingContext2D | undefined;
  let minMs = Infinity;
  let maxMs = -Infinity;
  let yOffset = 0;
  let threads: Record<string, Thread> = {};
  let blockList: Block[] = [];
  let scopes: Record<number, ScopeDesc> = {};
  let selectedRange: [number, number] | undefined;
  let viewRange: [number, number] | undefined;
  let beginPan: BeginPan | undefined;
  let beginSelect: BeginDetect | undefined;

  const client = new PerformanceAnalyticsClientImpl(
    new GrpcWebImpl("http://" + location.hostname + ":9090", {})
  );

  onMount(() => {
    const canvas = document.getElementById("canvas_timeline");

    if (!canvas || !(canvas instanceof HTMLCanvasElement)) {
      throw new Error("Canvas can't be found or is invalid");
    }

    const context = canvas.getContext("2d");

    if (!context) {
      throw new Error("Couldn't get context for canvas");
    }

    renderingContext = context;

    fetchProcessInfo();
  });

  async function fetchProcessInfo() {
    try {
      const { process } = await client.find_process({ processId: id });

      if (!process) {
        throw new Error(`Process ${id} not found`);
      }

      processList.push(process);
      fetchStreams(process);
      currentProcess = process;
      fetchChildren();
    } catch (error) {
      console.error(error);
      throw error;
    }
  }

  async function fetchStreams(process: Process) {
    try {
      const { streams } = await client.list_process_streams({
        processId: process.processId,
      });

      streams.forEach((stream) => {
        if (stream.tags.includes("cpu")) {
          threads[stream.streamId] = {
            streamInfo: stream,
            spanBlocks: [],
          };

          fetchBlocks(stream.streamId);
        }
      });
    } catch (error) {
      console.error(error);
      throw error;
    }
  }

  async function fetchChildren() {
    try {
      const { processes } = await client.list_process_children({
        processId: id,
      });

      processes.forEach((process) => {
        processList.push(process);

        fetchStreams(process);
      });
    } catch (error) {
      console.error(error);
      throw error;
    }
  }

  async function fetchBlocks(streamId: string) {
    try {
      const { blocks } = await client.list_stream_blocks({ streamId });

      blockList = blockList.concat(blocks);

      blocks.forEach(fetchBlockSpans);
    } catch (error) {
      console.error(error);
      throw error;
    }
  }

  async function fetchBlockSpans(block: Block) {
    const streamId = block.streamId;

    const process = findStreamProcess(streamId);

    if (!process) {
      throw new Error(`Process ${streamId} not found`);
    }

    const response = await client.block_spans({
      blockId: block.blockId,
      process,
      stream: threads[streamId].streamInfo,
    });

    response.scopes.forEach((scopeDesc) => {
      scopes[scopeDesc.hash] = scopeDesc;
    });

    minMs = Math.min(minMs, response.beginMs);
    maxMs = Math.max(maxMs, response.endMs);

    threads = {
      ...threads,
      [streamId]: {
        ...threads[streamId],
        spanBlocks: [...threads[streamId].spanBlocks, response],
      },
    };

    drawCanvas();
  }

  function findStreamProcess(streamId: string) {
    const stream = threads[streamId].streamInfo;

    return processList.find(
      (process) => process.processId === stream.processId
    );
  }

  function drawCanvas() {
    if (!canvas || !renderingContext) {
      return;
    }

    if (!currentProcess) {
      throw new Error("Current process not set");
    }

    canvas.height =
      window.innerHeight - canvas.getBoundingClientRect().top - 20;

    renderingContext.clearRect(0, 0, canvas.width, canvas.height);

    let threadVerticalOffset = yOffset;

    const parentStartTime = Date.parse(currentProcess?.startTime);

    for (const streamId in threads) {
      const childProcess = findStreamProcess(streamId);

      if (!childProcess) {
        throw new Error("Child process not found");
      }

      const childStartTime = Date.parse(childProcess.startTime);

      const maxDepth = drawThread(
        threads[streamId],
        threadVerticalOffset,
        childStartTime - parentStartTime
      );

      if (maxDepth) {
        threadVerticalOffset += (maxDepth + 2) * 20;
      }
    }

    drawSelectedRange();
  }

  function drawSelectedRange() {
    if (!canvas || !renderingContext) {
      return;
    }

    if (!selectedRange) {
      return;
    }

    const [begin, end] = getViewRange();
    const invTimeSpan = 1.0 / (end - begin);
    const canvasWidth = canvas.clientWidth;
    const canvasHeight = canvas.clientHeight;
    const msToPixelsFactor = invTimeSpan * canvasWidth;
    const [beginSelection, endSelection] = selectedRange;
    const beginPixels = (beginSelection - begin) * msToPixelsFactor;
    const endPixels = (endSelection - begin) * msToPixelsFactor;

    renderingContext.fillStyle = "rgba(64, 64, 200, 0.2)";
    renderingContext.fillRect(
      beginPixels,
      0,
      endPixels - beginPixels,
      canvasHeight
    );
  }

  function drawThread(
    thread: Thread,
    threadVerticalOffset: number,
    offsetMs: number
  ) {
    if (!canvas || !renderingContext) {
      return;
    }

    const [begin, end] = getViewRange();
    const invTimeSpan = 1.0 / (end - begin);
    const canvasWidth = canvas.clientWidth;
    const msToPixelsFactor = invTimeSpan * canvasWidth;

    renderingContext.font = "15px arial";

    const testString = "<>_w";
    const testTextMetrics = renderingContext.measureText(testString);
    const characterWidth = testTextMetrics.width / testString.length;
    const characterHeight = testTextMetrics.actualBoundingBoxAscent;

    let maxDepth = 0;

    thread.spanBlocks.forEach((blockSpans) => {
      maxDepth = Math.max(maxDepth, blockSpans.maxDepth);

      blockSpans.spans.forEach(({ beginMs, endMs, depth, scopeHash }) => {
        if (!renderingContext) {
          throw new Error("Rendering context not available");
        }

        const beginSpan = beginMs + offsetMs;
        const endSpan = endMs + offsetMs;
        const beginPixels = (beginSpan - begin) * msToPixelsFactor;
        const endPixels = (endSpan - begin) * msToPixelsFactor;
        const callWidth = endPixels - beginPixels;

        const offsetY = threadVerticalOffset + depth * 20;

        if (depth % 2 === 0) {
          renderingContext.fillStyle = "#7DF9FF";
        } else {
          renderingContext.fillStyle = "#A0A0CC";
        }

        renderingContext.fillRect(beginPixels, offsetY, callWidth, 20);

        const { name } = scopes[scopeHash];

        if (callWidth > characterWidth * 5) {
          const nbChars = Math.floor(callWidth / characterWidth);

          renderingContext.fillStyle = "#000000";

          const extraHeight = 0.5 * (20 - characterHeight);
          const caption = name + " " + formatExecutionTime(endSpan - beginSpan);

          renderingContext.fillText(
            caption.slice(0, nbChars),
            beginPixels + 5,
            offsetY + characterHeight + extraHeight,
            callWidth
          );
        }
      });
    });

    return maxDepth;
  }

  function getViewRange(): [number, number] {
    if (viewRange) {
      return viewRange;
    }

    return [minMs, maxMs];
  }

  function onPan(event: MouseEvent) {
    if (!canvas) {
      throw new Error("Canvas can't be found");
    }

    if (!beginPan) {
      beginPan = {
        beginMouseX: event.offsetX,
        beginMouseY: event.offsetY,
        viewRange: getViewRange(),
        beginYOffset: yOffset,
      };
    }

    const factor =
      (beginPan.viewRange[1] - beginPan.viewRange[0]) / canvas.width;
    const offsetMs = factor * (beginPan.beginMouseX - event.offsetX);

    viewRange = [
      beginPan.viewRange[0] + offsetMs,
      beginPan.viewRange[1] + offsetMs,
    ];
    yOffset = beginPan.beginYOffset + event.offsetY - beginPan.beginMouseY;
    drawCanvas();
  }

  function onSelectRange(event: MouseEvent) {
    if (!canvas) {
      throw new Error("Canvas can't be found");
    }

    if (!beginSelect) {
      beginSelect = {
        beginMouseX: event.offsetX,
      };
    }

    const viewRange = getViewRange();
    const factor = (viewRange[1] - viewRange[0]) / canvas.width;
    const beginTime = viewRange[0] + factor * beginSelect.beginMouseX;
    const endTime = viewRange[0] + factor * event.offsetX;

    selectedRange = [beginTime, endTime];

    drawCanvas();
  }

  function onMouseDown(event: MouseEvent) {
    if (event.shiftKey) {
      beginSelect = undefined;
      selectedRange = undefined;
      drawCanvas();
    }
  }

  function onMouseMove(event: MouseEvent) {
    if (event.buttons !== 1) {
      beginPan = undefined;
      beginSelect = undefined;

      return;
    }

    if (event.shiftKey) {
      onSelectRange(event);
    } else {
      onPan(event);
    }
  }

  function onZoom(event: WheelEvent) {
    if (!canvas) {
      throw new Error("Canvas can't be found");
    }

    const speed = 0.75;
    const factor = event.deltaY > 0 ? 1.0 / speed : speed;
    const oldRange = getViewRange();
    const length = oldRange[1] - oldRange[0];
    const newLength = length * factor;
    const pctCursor = event.offsetX / canvas.width;
    const pivot = oldRange[0] + length * pctCursor;

    viewRange = [
      pivot - newLength * pctCursor,
      pivot + newLength * (1 - pctCursor),
    ];

    drawCanvas();
  }
</script>

<div>
  {#if currentProcess}
    <div>
      <div>{currentProcess.exe} {currentProcess.processId}</div>
      {#if currentProcess.parentProcessId}
        <div class="parent-process">
          <a href={`/timeline/${currentProcess.parentProcessId}`} use:link>
            Parent timeline
          </a>
        </div>
      {/if}
      {#if selectedRange}
        <button class="call-graph-button">
          <a
            href={`/cumulative-call-graph?process=${currentProcess.processId}&begin=${selectedRange[0]}&end=${selectedRange[1]}`}
            use:link
          >
            Cumulative Call Graph
          </a>
        </button>
      {/if}
    </div>
  {/if}
  <canvas
    class="timeline-canvas"
    bind:this={canvas}
    id="canvas_timeline"
    width="1024px"
    on:wheel|preventDefault={onZoom}
    on:mousemove={onMouseMove}
    on:mousedown={onMouseDown}
  />
</div>

<style lang="postcss">
  .parent-process {
    @apply text-[#42b983] underline;
  }

  .timeline-canvas {
    margin: auto;
  }

  .call-graph-button {
    background-color: rgba(64, 64, 200, 0.2);
    border: 1px solid;
    transition-duration: 0.4s;
    border-radius: 4px;
  }

  .call-graph-button:hover {
    background-color: rgba(64, 64, 200, 1);
    color: white;
    border: 1px solid;
  }
</style>

// client/analytics-web/src/views/Timeline.vue
<template>
  <div>
    <template v-bind:process="current_process">
      <div v-if="current_process">
        <div>{{ current_process.getExe() }} {{ current_process.getProcessId() }}</div>
        <div v-if="current_process.getParentProcessId() != ''">
          <router-link
            v-bind:to="{ name: 'Timeline', params: {process_id: current_process.getParentProcessId() } }">
            Parent timeline
          </router-link>
        </div>
      </div>
    </template>
    <canvas id="canvas_timeline"
            width="1024px"
            height="768px"
            v-on:wheel.prevent="onZoom"
            v-on:mousemove="onMouseMove"
            />
  </div>
</template>

<script>
import { ListProcessChildrenRequest, BlockSpansRequest, ListStreamBlocksRequest, ListProcessStreamsRequest, FindProcessRequest, PerformanceAnalyticsClient } from '../proto/analytics_grpc_web_pb'

function findStreamProcess (streamId) {
  const stream = this.threads[streamId].streamInfo
  const process = this.process_list.find(process => process.getProcessId() === stream.getProcessId())
  return process
}

function fetchBlockSpans (block) {
  const streamId = block.getStreamId()
  const stream = this.threads[streamId].streamInfo
  const process = this.findStreamProcess(streamId)
  const request = new BlockSpansRequest()
  request.setProcess(process)
  request.setStream(stream)
  request.setBlockId(block.getBlockId())
  this.client.block_spans(request, null, (err, response) => {
    if (err) {
      console.error('error in block_spans', err)
    } else {
      response.getScopesList().forEach(scopeDesc => {
        this.scopes[scopeDesc.getHash()] = scopeDesc
      })
      this.min_ms = Math.min(this.min_ms, response.getBeginMs())
      this.max_ms = Math.max(this.max_ms, response.getEndMs())
      this.threads[streamId].spanBlocks.push(response)
      this.drawCanvas()
    }
  })
}

function fetchBlocks (streamId) {
  try {
    var request = new ListStreamBlocksRequest()
    request.setStreamId(streamId)
    this.client.list_stream_blocks(request, null, (err, response) => {
      if (err) {
        console.error('error in list_stream_blocks', err)
      } else {
        const newBlocks = response.getBlocksList()
        this.block_list = this.block_list.concat(newBlocks)
        newBlocks.forEach(block => this.fetchBlockSpans(block))
      }
    })
  } catch (err) {
    console.error(err.message)
    throw err
  }
}

function fetchStreams (process) {
  try {
    var request = new ListProcessStreamsRequest()
    request.setProcessId(process.getProcessId())
    this.client.list_process_streams(request, null, (err, response) => {
      if (err) {
        console.error('error in list_process_streams', err)
      } else {
        response.getStreamsList().forEach(stream => {
          if (stream.getTagsList().includes('cpu')) {
            this.threads[stream.getStreamId()] = {
              streamInfo: stream,
              spanBlocks: []
            }
            this.fetchBlocks(stream.getStreamId())
          }
        })
      }
    })
  } catch (err) {
    console.error(err.message)
    throw err
  }
}

function fetchChildren () {
  var listChildrenRequest = new ListProcessChildrenRequest()
  listChildrenRequest.setProcessId(this.process_id)
  this.client.list_process_children(listChildrenRequest, null, (err, response) => {
    if (err) {
      console.error('error in list_process_children', err)
    } else {
      response.getProcessesList().forEach(process => {
        this.process_list.push(process)
        this.fetchStreams(process)
      })
    }
  })
}

function fetchProcessInfo () {
  try {
    var findProcessRequest = new FindProcessRequest()
    findProcessRequest.setProcessId(this.process_id)
    this.client.find_process(findProcessRequest, null, (err, response) => {
      if (err) {
        console.error('error in find_process', err)
      } else {
        const process = response.getProcess()
        this.process_list.push(process)
        this.fetchStreams(process)
        this.current_process = process
        this.fetchChildren()
      }
    })
  } catch (err) {
    console.error(err.message)
    throw err
  }
}

function onTimelineCreated () {
  this.$watch(
    () => this.$route.params,
    (toParams, previousParams) => {
      this.reset(toParams.process_id)
    }
  )
  this.client = new PerformanceAnalyticsClient('http://' + location.hostname + ':9090', null, null)
  this.fetchProcessInfo()
}

function onMounted () {
  const canvas = document.getElementById('canvas_timeline')
  this.renderingContext = canvas.getContext('2d')
}

function formatExecutionTime (time) {
  let unit = 'ms'
  if (time < 1) {
    unit = 'us'
    time = time * 1000
    return time.toFixed(3) + ' ' + unit
  }
  if (time > 1000) {
    unit = 'seconds'
    time = time / 1000
  }
  return time.toFixed(3) + ' ' + unit
}

function drawThread (thread, threadVerticalOffset, offsetMs) {
  const viewRange = this.getViewRange()
  const begin = viewRange[0]
  const end = viewRange[1]
  const invTimeSpan = 1.0 / (end - begin)
  const canvas = document.getElementById('canvas_timeline')
  const canvasWidth = canvas.clientWidth
  const msToPixelsFactor = invTimeSpan * canvasWidth
  this.renderingContext.font = '15px arial'
  const testString = '<>_w'
  const testTextMetrics = this.renderingContext.measureText(testString)
  const characterWidth = testTextMetrics.width / testString.length
  const characterHeight = testTextMetrics.actualBoundingBoxAscent
  let maxDepth = 0
  thread.spanBlocks.forEach(blockSpans => {
    maxDepth = Math.max(maxDepth, blockSpans.getMaxDepth())
    blockSpans.getSpansList().forEach(span => {
      const beginSpan = span.getBeginMs() + offsetMs
      const endSpan = span.getEndMs() + offsetMs
      const beginPixels = (beginSpan - begin) * msToPixelsFactor
      const endPixels = (endSpan - begin) * msToPixelsFactor
      const callWidth = endPixels - beginPixels
      const depth = span.getDepth()
      const offsetY = threadVerticalOffset + (depth * 20)
      if (depth % 2 === 0) {
        this.renderingContext.fillStyle = '#7DF9FF'
      } else {
        this.renderingContext.fillStyle = '#A0A0CC'
      }
      this.renderingContext.fillRect(beginPixels, offsetY, callWidth, 20)
      const scope = this.scopes[span.getScopeHash()]
      if (callWidth > (characterWidth * 5)) {
        const nbChars = Math.floor(callWidth / characterWidth)
        this.renderingContext.fillStyle = '#000000'
        const extraHeight = 0.5 * (20 - characterHeight)
        const name = scope.getName()
        const caption = name + ' ' + formatExecutionTime(endSpan - beginSpan)
        this.renderingContext.fillText(caption.slice(0, nbChars), beginPixels + 5, offsetY + characterHeight + extraHeight, callWidth)
      }
    })
  })
  return maxDepth
}

function drawSelectedRange () {
  if (this.selected_range === undefined) {
    return
  }
  const viewRange = this.getViewRange()
  const begin = viewRange[0]
  const end = viewRange[1]
  const invTimeSpan = 1.0 / (end - begin)
  const canvas = document.getElementById('canvas_timeline')
  const canvasWidth = canvas.clientWidth
  const canvasHeight = canvas.clientHeight
  const msToPixelsFactor = invTimeSpan * canvasWidth
  const beginSelection = this.selected_range[0]
  const endSelection = this.selected_range[1]
  const beginPixels = (beginSelection - begin) * msToPixelsFactor
  const endPixels = (endSelection - begin) * msToPixelsFactor
  this.renderingContext.fillStyle = 'rgba(64, 64, 200, 0.2)'
  this.renderingContext.fillRect(beginPixels, 0, endPixels - beginPixels, canvasHeight)
}

function drawCanvas () {
  const canvas = document.getElementById('canvas_timeline')
  canvas.height = window.innerHeight - canvas.getBoundingClientRect().top - 20
  this.renderingContext.clearRect(0, 0, canvas.width, canvas.height)
  let threadVerticalOffset = this.y_offset
  const parentStartTime = Date.parse(this.current_process.getStartTime())
  for (const streamId in this.threads) {
    const childProcess = this.findStreamProcess(streamId)
    const childStartTime = Date.parse(childProcess.getStartTime())
    const maxDepth = this.drawThread(this.threads[streamId], threadVerticalOffset, childStartTime - parentStartTime)
    threadVerticalOffset += (maxDepth + 2) * 20
  }
  this.drawSelectedRange()
}

function onPan (evt) {
  if (!this.begin_pan) {
    this.begin_pan = {
      beginMouseX: evt.offsetX,
      beginMouseY: evt.offsetY,
      viewRange: this.getViewRange(),
      beginYOffset: this.y_offset
    }
  }
  const canvas = document.getElementById('canvas_timeline')
  const factor = (this.begin_pan.viewRange[1] - this.begin_pan.viewRange[0]) / canvas.width
  const offsetMs = factor * (this.begin_pan.beginMouseX - evt.offsetX)
  this.view_range = [this.begin_pan.viewRange[0] + offsetMs, this.begin_pan.viewRange[1] + offsetMs]
  this.y_offset = this.begin_pan.beginYOffset + evt.offsetY - this.begin_pan.beginMouseY
  this.drawCanvas()
}

function onSelectRange (evt) {
  if (!this.begin_select) {
    this.begin_select = {
      beginMouseX: evt.offsetX
    }
  }
  const canvas = document.getElementById('canvas_timeline')
  const viewRange = this.getViewRange()
  const factor = (viewRange[1] - viewRange[0]) / canvas.width
  const beginTime = viewRange[0] + (factor * this.begin_select.beginMouseX)
  const endTime = viewRange[0] + (factor * evt.offsetX)
  this.selected_range = [beginTime, endTime]
  this.drawCanvas()
}

function onMouseMove (evt) {
  if (evt.buttons !== 1) {
    this.begin_pan = undefined
    this.begin_select = undefined
    return
  }
  if (evt.shiftKey) {
    this.onSelectRange(evt)
  } else {
    this.onPan(evt)
  }
}

function onZoom (evt) {
  const speed = 1.25
  const factor = evt.wheelDeltaY > 0 ? (1.0 / speed) : speed
  const oldRange = this.getViewRange()
  const length = oldRange[1] - oldRange[0]
  const newLength = length * factor
  const canvas = document.getElementById('canvas_timeline')
  const pctCursor = evt.offsetX / canvas.width
  const pivot = oldRange[0] + (length * pctCursor)
  this.view_range = [pivot - (newLength * pctCursor), pivot + (newLength * (1 - pctCursor))]
  this.drawCanvas()
}

function getViewRange () {
  if (this.view_range) {
    return this.view_range
  }
  return [this.min_ms, this.max_ms]
}

function reset (processId) {
  this.process_id = processId
  this.block_list = []
  this.process_list = []
  this.current_process = undefined
  this.scopes = {}
  this.threads = []
  this.min_ms = Infinity
  this.max_ms = -Infinity
  this.view_range = undefined
  this.begin_pan = undefined
  this.begin_select = undefined
  this.y_offset = 0
  this.selected_range = undefined
  this.fetchProcessInfo()
}

export default {
  name: 'Timeline',
  props: {
    process_id: {
      type: String,
      default: 'no'
    }
  },
  created: onTimelineCreated,
  mounted: onMounted,
  data: function () {
    return {
      block_list: [],
      process_list: [],
      current_process: undefined,
      scopes: {},
      threads: {},
      min_ms: Infinity,
      max_ms: -Infinity,
      view_range: undefined,
      begin_pan: undefined,
      begin_select: undefined,
      y_offset: 0,
      selected_range: undefined
    }
  },
  methods: {
    drawCanvas: drawCanvas,
    drawSelectedRange: drawSelectedRange,
    drawThread: drawThread,
    fetchBlockSpans: fetchBlockSpans,
    fetchBlocks: fetchBlocks,
    fetchChildren: fetchChildren,
    fetchProcessInfo: fetchProcessInfo,
    fetchStreams: fetchStreams,
    findStreamProcess: findStreamProcess,
    getViewRange: getViewRange,
    onMouseMove: onMouseMove,
    onPan: onPan,
    onSelectRange: onSelectRange,
    onZoom: onZoom,
    reset: reset
  }
}
</script>
